name: run-pytest
run-name: Run pytest on unit tests

on:
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Upgrade pip
      run: pip install --upgrade pip

    - name: Install pytest
      run: pip install pytest

    - name: Run unit tests in verbose mode
      run: pytest -v -m unit


