name: Use our secret (but not really)

on:
  workflow_dispatch:

jobs:
  try-to-print-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Print our secret
      env:
        MY_SECRET: ${{ secrets.SECRET_1 }}
      run: echo "$MY_SECRET"


