name: Use our secret (but not really) - take 2

on:
  workflow_dispatch:

jobs:
  try-to-print-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Print our secret
      env:
        MY_SECRET: ${{ secrets.SECRET_1 }}
      run: echo This is my secret: "$MY_SECRET"
    - name: Print the env
      env:
        MY_SECRET: ${{ secrets.SECRET_1 }}
      run: printenv
      



